# .github/workflows/CI_test_workflow_call.yml in Project B

name: CI_test_workflow_call

on:
  workflow_dispatch:

env:  # Global environment variables for the workflow
  FINE_GRAINED_PAT: ${{ secrets.FINE_GRAINED_PAT }}
  REPO_OWNER: ${{ secrets.REPO_OWNER }}
  REPO_NAME: ${{ secrets.REPO_NAME }}
  DATA_FILE_PATH: ${{ secrets.DATA_FILE_PATH }}

jobs:
  run-python-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate HTML Report
        id: generate_html_report
        run: |
          html_report=$(python main.py)
          echo "html_report<<EOF" >> $GITHUB_ENV
          echo "$html_report" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit updated files
        run: |
          git add data/predicted_numbers.csv
          git add data/bayesian_model.pkl
          git commit -m "Update model and predictions [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Email with HTML Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Daily Sequence Forecaster - Predicted Numbers'
          from: 'Notification Service <notification.service1988@gmail.com>'
          html_body: ${{ env.html_report }}
          to: ${{ secrets.EMAIL_RECIPIENT }}
