name: Daily Sequence Forecaster

on:
  workflow_dispatch: # Allows for manual workflow trigger
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC

jobs:
  run-python-project:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Specify your Python version

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run Python Script
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_PAT }} # Securely access PAT from GitHub secrets
        run: |
          python main.py

      # Step 5: Set Git user for commit
      - name: Set Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Step 6: Commit and Push Updates
      - name: Commit and Push Predicted Numbers
        env:
          GITHUB_TOKEN: ${{ secrets.FINE_GRAINED_PAT }}
        run: |
          git add data/predicted_numbers.csv
          git commit -m "Update predicted numbers [skip ci]" || echo "No changes to commit"
          git push
